name: Black

on: [pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Create lock file
        run: poetry lock --no-update
      - name: Add dependencies with Poetry
        run: poetry install
      - name: Run Black
        run: poetry run black
