name: Black

on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Create lock file
        run: poetry lock --no-update

      - name: Add dependencies with Poetry
        run: poetry install

      - name: Get modified files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: Run Black
        shell: 'bash'
        working-directory: ${{ github.action_path }}
        run: |
          mapfile -d ',' -t modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for file in "${modified_files[@]}"; do
            if [[ "${file}" == *.py ]]; then
              poetry run black check "${file}" -v --no-cache
            fi
          done
